name: geoflutterfire_example
description: Demonstrates how to use the geoflutterfire plugin.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  geoflutterfire:
    path: ../

  cloud_firestore: ^4.17.5
  google_maps_flutter: ^2.9.0

flutter:
  uses-material-design: true
